<?xml version="1.0" encoding="utf-8"?><Database Name="FDA_FOOD_ANGULAR" Class="SEARCH_SYSTEMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.130;Initial Catalog=FDA_FOOD_ANGULAR;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FDA_FOOD_ANGULARConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.REQUESTTYPE" Member="REQUESTTYPEs">
    <Type Name="REQUESTTYPE">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TYPEREQUEST" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.STATUS_MASTER" Member="STATUS_MASTERs">
    <Type Name="STATUS_MASTER">
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STATUS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_CUS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CAL" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>